export const EMOJIS = [
  {
    id: 1,
    english: "Milk",
    spanish: "La Leche",
    emoji: "🥛",
  },
  {
    id: 2,
    english: "Onion",
    spanish: "La Cebolla",
    emoji: "🧅",
  },
  {
    id: 3,
    english: "Bread",
    spanish: "El Pan",
    emoji: "🍞",
  },
  {
    id: 4,
    english: "Corn",
    spanish: "El Maíz",
    emoji: "🌽",
  },
  {
    id: 5,
    english: "Cucumber",
    spanish: "El Pepino",
    emoji: "🥒",
  },
  {
    id: 6,
    english: "Garlic",
    spanish: "El Ajo",
    emoji: "🧄",
  },
  {
    id: 7,
    english: "Hot Pepper",
    spanish: "El Chile",
    emoji: "🌶️",
  },
  {
    id: 8,
    english: "Red Apple",
    spanish: "La Manzana Roja",
    emoji: "🍎",
  },
  {
    id: 9,
    english: "Green Apple",
    spanish: "La Manzana Verde",
    emoji: "🍏",
  },
  {
    id: 10,
    english: "Mushroom",
    spanish: "El Hongo",
    emoji: "🍄",
  },
  {
    id: 11,
    english: "Carrot",
    spanish: "La Zanahoria",
    emoji: "🥕",
  },
  {
    id: 12,
    english: "Cheese",
    spanish: "El Queso",
    emoji: "🧀",
  },
  {
    id: 13,
    english: "Shrimp",
    spanish: "El Camaron",
    emoji: "🍤",
  },
  {
    id: 14,
    english: "Tomato",
    spanish: "El Tomate",
    emoji: "🍅",
  },
  {
    id: 15,
    english: "Strawberry",
    spanish: "La Fresa",
    emoji: "🍓",
  },
  {
    id: 16,
    english: "Avocado",
    spanish: "El Aguacate",
    emoji: "🥑",
  },
  {
    id: 17,
    english: "Pineapple",
    spanish: "La Piña",
    emoji: "🍍",
  },
  {
    id: 18,
    english: "Egg",
    spanish: "El Huevo",
    emoji: "🥚",
  },
  {
    id: 19,
    english: "Cherry",
    spanish: "La Cereza",
    emoji: "🍒",
  },
  {
    id: 20,
    english: "Lemon",
    spanish: "El Limon",
    emoji: "🍋",
  },
  {
    id: 21,
    english: "Oyster",
    spanish: "La Ostra",
    emoji: "🦪",
  },
  {
    id: 22,
    english: "Coconut",
    spanish: "El Coco",
    emoji: "🥥",
  },
  {
    id: 23,
    english: "Watermelon",
    spanish: "La Sandia",
    emoji: "🍉",
  },
  {
    id: 24,
    english: "Peanuts",
    spanish: "Los Manís",
    emoji: "🥜",
  },
  {
    id: 25,
    english: "Chicken",
    spanish: "El Pollo",
    emoji: "🍗",
  },
  {
    id: 26,
    english: "Steak",
    spanish: "El filete",
    emoji: "🥩",
  },
  {
    id: 27,
    english: "Ice Cream",
    spanish: "El Helado",
    emoji: "🍦",
  },
  {
    id: 28,
    english: "Grapes",
    spanish: "Las Uvas",
    emoji: "🍇",
  },
  {
    id: 29,
    english: "Orange",
    spanish: "La Naranja",
    emoji: "🍊",
  },
  {
    id: 30,
    english: "Peach",
    spanish: "El Durazno",
    emoji: "🍑",
  },
];
