export const EMOJIS = [
  {
    id: 1,
    english: "The Milk",
    spanish: "La Leche",
    emoji: "🥛",
  },
  {
    id: 2,
    english: "The Onion",
    spanish: "La Cebolla",
    emoji: "🧅",
  },
  {
    id: 3,
    english: "The Bread",
    spanish: "El Pan",
    emoji: "🍞",
  },
  {
    id: 4,
    english: "The Corn",
    spanish: "El Maíz",
    emoji: "🌽",
  },
  {
    id: 5,
    english: "The Cucumber",
    spanish: "El Pepino",
    emoji: "🥒",
  },
  {
    id: 6,
    english: "The Garlic",
    spanish: "El Ajo",
    emoji: "🧄",
  },
  {
    id: 7,
    english: "The Hot Pepper",
    spanish: "El Chile",
    emoji: "🌶️",
  },
  {
    id: 8,
    english: "The Red Apple",
    spanish: "La Manzana Roja",
    emoji: "🍎",
  },
  {
    id: 9,
    english: "The Green Apple",
    spanish: "La Manzana Verde",
    emoji: "🍏",
  },
  {
    id: 10,
    english: "The Mushroom",
    spanish: "El Hongo",
    emoji: "🍄",
  },
  {
    id: 11,
    english: "The Carrot",
    spanish: "La Zanahoria",
    emoji: "🥕",
  },
  {
    id: 12,
    english: "The Cheese",
    spanish: "El Queso",
    emoji: "🧀",
  },
  {
    id: 13,
    english: "The Shrimp",
    spanish: "El Camaron",
    emoji: "🍤",
  },
  {
    id: 14,
    english: "The Tomato",
    spanish: "El Tomate",
    emoji: "🍅",
  },
  {
    id: 15,
    english: "The Strawberry",
    spanish: "La Fresa",
    emoji: "🍓",
  },
  {
    id: 16,
    english: "The Avocado",
    spanish: "El Aguacate",
    emoji: "🥑",
  },
  {
    id: 17,
    english: "The Pineapple",
    spanish: "La Piña",
    emoji: "🍍",
  },
  {
    id: 18,
    english: "The Egg",
    spanish: "El Huevo",
    emoji: "🥚",
  },
  {
    id: 19,
    english: "The Cherry",
    spanish: "La Cereza",
    emoji: "🍒",
  },
  {
    id: 20,
    english: "The Lemon",
    spanish: "El Limon",
    emoji: "🍋",
  },
  {
    id: 21,
    english: "The Oyster",
    spanish: "El Ostra",
    emoji: "🦪",
  },
  {
    id: 22,
    english: "The Coconut",
    spanish: "El Coco",
    emoji: "🥥",
  },
  {
    id: 23,
    english: "The Watermelon",
    spanish: "La Sandia",
    emoji: "🍉",
  },
  {
    id: 24,
    english: "The Peanuts",
    spanish: "Los Manís",
    emoji: "🥜",
  },
  {
    id: 25,
    english: "The Chicken",
    spanish: "El Pollo",
    emoji: "🍗",
  },
  {
    id: 26,
    english: "The Meat",
    spanish: "El Carne",
    emoji: "🥩",
  },
  {
    id: 27,
    english: "The Ice Cream",
    spanish: "El Helado",
    emoji: "🍦",
  },
  {
    id: 28,
    english: "The Grapes",
    spanish: "Las Uvas",
    emoji: "🍇",
  },
  {
    id: 29,
    english: "The Orange",
    spanish: "La Naranja",
    emoji: "🍊",
  },
  {
    id: 30,
    english: "The Peach",
    spanish: "El Durazno",
    emoji: "🍑",
  },
];
